name: call-trusted-reusable

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  delegated:
    permissions:
      id-token: write
      contents: read
    uses: zashk0-labs/bb-oidc-rwref-20260921-045231/.github/workflows/trusted.yml@main
